#!/usr/bin/env python3
"""Convert a PEM CA bundle into a C const array consumed by ce_http_tls.c.

Usage: tools/gen_ca_bundle.py <cacert.pem> <output.c>
"""
import sys, pathlib

if len(sys.argv) != 3:
    sys.exit("usage: gen_ca_bundle.py <input.pem> <output.c>")

pem = pathlib.Path(sys.argv[1]).read_bytes()
out = pathlib.Path(sys.argv[2])

# Sanity: trim to BEGIN/END CERTIFICATE blocks only, drop banner comments.
lines = []
keep = False
for line in pem.splitlines():
    if line.startswith(b"-----BEGIN CERTIFICATE-----"):
        keep = True
    if keep:
        lines.append(line)
    if line.startswith(b"-----END CERTIFICATE-----"):
        keep = False
        lines.append(b"")  # blank line between certs
clean = b"\n".join(lines)
# wolfSSL is happy with LF line endings.

with out.open("w") as f:
    f.write('/* ce_http_ca_bundle.c: Mozilla root CA PEM bundle.\n')
    f.write(' *\n')
    f.write(' * Generated by tools/gen_ca_bundle.py from upstream bundle\n')
    f.write(' * (Mozilla / curl.se / ca-certificates). Loaded once at fetcher\n')
    f.write(' * registration via wolfSSL_CTX_load_verify_buffer; no filesystem\n')
    f.write(' * dependency on the device. Regenerate by re-running the script\n')
    f.write(' * against a refreshed source bundle.\n')
    f.write(' */\n')
    f.write('#include <stddef.h>\n\n')
    f.write('const unsigned char ce_http_ca_bundle_pem[] = {\n')
    cols = 16
    for i in range(0, len(clean), cols):
        chunk = clean[i:i+cols]
        f.write('    ' + ','.join(f'0x{b:02x}' for b in chunk) + ',\n')
    f.write('    0x00\n')
    f.write('};\n\n')
    f.write(f'const size_t ce_http_ca_bundle_pem_len = {len(clean)};\n')

print(f"wrote {out} ({len(clean)} bytes of PEM, {lines.count(b'-----BEGIN CERTIFICATE-----') if False else clean.count(b'-----BEGIN CERTIFICATE-----')} certificates)")
